title: "// random blog;"
email: your-email@example.com
description: >-
  random - /ˈrandəm/ <br/>
  adjective > STATISTICS<br/>
  &nbsp;&nbsp;governed by or involving equal chances for each item<br/>
  &nbsp;&nbsp;&nbsp;&nbsp;<a href='https://languages.oup.com/google-dictionary-en/'>Oxford Languages</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://misstickles.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: misstickles
github_repo: misstickles.github.io
github: [metadata]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
highlighter: rouge

# Build settings
#theme: minima
#theme: jekyll-swiss
#theme_color: yellow

kramdown:
  auto_ids: true

plugins:
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
