title: "// probably; definitely"
heading: "Jo Faircloth"
subheading: "Software Application Engineer<br /><i class='fas fa-map-marker-alt'></i> Mid Sussex, UK</a>"
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://misstickles.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: misstickles
github_repo: misstickles.github.io
github_url: https://github.com/misstickles/misstickles.github.io
github: [metadata]

markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  input: GFM

# themes
# cv, https://github.com/sharu725/online-cv
theme_skin: orange # blue, turquoise, green, berry, orange, ceramic

# yat
yat:
  date_format: "%d %B %Y"
# Pagination setting
# paginate: 5
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
theme_color: "spacegrey"
#
# Custom color as below:
# theme_color: "#882250"
night_mode: "manual"
# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
